### ISSUE TITLE
Can't map content or custom fields

### ISSUE THREAD

**Issue by snaffle** [joolanders/ytp-source-k2#8]
Firstly, was super pleased to see this released as a dynamic source for Yootheme and thanks greatly to the sponsor for making it happen!

I've installed the latest Development version of K2 - v2.11.0 [Build 20220511] - and I'm running Joomla 3.10.8

I have the source installed correctly and available in the builder but sadly I can only get the Title, Image and Link of any K2 item to map to a builder element.

See attached screenshot showing a Panel Slider where the Title, Image and Link map correctly but not the content as such.

I've also been through and tested a range of custom fields that we have set up and they don't seem to work either.

Any ideas what might be wrong?

![k2-source-content-not-working](https://user-images.githubusercontent.com/6090719/170137173-74516406-f294-4a0f-8157-38d8d0f6d2fa.png)

**Comment by miljan-aleksic** [comment]
Hi Nathan,

the integration didn't had the chance to be tested in the wide, so this is great. Can you open the browser console and see if there is any issue being displayed? If so, try to see it details and attach a screenshot.

**Comment by snaffle** [comment]
Hi Miljan, thanks for the quick reply.

Sadly there is no message at all in the browser console other than confirmation that a small piece of JQuery has run to move the navigation arrows either side of the navigation dots, but I can't imagine that's causing the problem as it runs after the page has loaded.

This is running on a development site so you are welcome to have a look yourself and I can provide you with admin access if that helps.

The dev site is:

[https://dev.sane.org](url)

And the panel slider is the one with the yellow background half way down the page.

![k2-source-content-console-no-message](https://user-images.githubusercontent.com/6090719/170152896-2b41a81a-de56-4b2a-ba3e-42e0e90510fb.png)

**Comment by snaffle** [comment]
Also, the first slide in the panel does actually have content, but it's a static slide and just an example of how it's meant to look.

**Comment by miljan-aleksic** [comment]
Source PHP related errors are catched and silented by the ytp framework. only to be shown as an error in the browser console while in the customizer. Make sure you have error repoting set to maximum and try again.

Otherwise an admin access would be great, just consider this is a public issue, but I could delete that info right after.

**Comment by snaffle** [comment]
Ah I see, did not know that.

Ok so I've turned that on and it did indeed generate some errors in the builder - screenshot attached together with an export of the console log which is showing a "Call to a member function get() on string" type error.

I'm happy for you to use this site for testing if that's helpful so have set up an admin account as follows:

login: miljan
pass: qHG358&$IKL$ahjz

And yes if we can delete that once you have it that would be be good :-)

Admin url is the standard /administrator

Error reporting is currently set to Maximum.

![k2-source-content-console-message](https://user-images.githubusercontent.com/6090719/170155678-10120382-12d5-42c2-a7ff-1fcfba48aa02.png)

[console-export-2022-5-25_10-48-16.txt](https://github.com/joolanders/ytp-source-k2/files/8767110/console-export-2022-5-25_10-48-16.txt)

**Comment by snaffle** [comment]
Also, with Maxium error reporting enable have noticed the rest of the page isn't loading at all after the top Builder section... no doubt being caused by the error.

**Comment by miljan-aleksic** [comment]
Alright, that's a lead! I will take a look asap, creds removed ;)

**Comment by snaffle** [comment]
And not sure if it's relevant, but on a standard K2 article page with max error reporting turned on it's now showing the following:

Notice: Undefined property: stdClass::$tags in /home/sanedev/public_html/templates/yootheme_sane/modules/builder-source-k2/src/TemplateListener.php on line 21

Warning: array_column() expects parameter 1 to be array, null given in /home/sanedev/public_html/templates/yootheme_sane/modules/builder-source-k2/src/TemplateListener.php on line 21

[https://dev.sane.org/peer-support/connect-with-a-peer-worker](url)

**Comment by snaffle** [comment]
I do actually need to keep working on this site so I'm going to turn the error reporting down as it's preventing me doing that at the moment and can see that you're not logged in... but if you need to turn it on, just go ahead and change it... I'll realise pretty quickly :-)

**Comment by miljan-aleksic** [comment]
Nathan,

I had to get creative in order to install the fixes without requiring ftp access, and I might got the source files copied in the wrong folder in the first attempt. Please check if `emplates/yootheme_sane/src` and `templates/yootheme_sane/templates`  folders exist and delete them.

As for the PHP warning, it is fixed now. Please test it and let me know if there is any issue left.

**Comment by snaffle** [comment]
Hi Miljan,

I did actually have a couple of header overrides in the templates/yootheme_sane/templates folder so have deleted the meta.php and tags.php files that were in there instead and removed the /src folder.

Sadly though, it's still not working but with a different error this time from the Builder - see attached and console log file.

I've also installed Phoca Commander, a file manager that should make it a bit easier to upload files... and can provide FTP if necessary.

So it's looks it's closer but still not quite working.

![k2-source-content-console-message--20220526](https://user-images.githubusercontent.com/6090719/170365821-9abda1a5-d1e2-4bd5-b600-cde1ad9177c9.png)

[console-export-2022-5-26_6-49-58.txt](https://github.com/joolanders/ytp-source-k2/files/8774476/console-export-2022-5-26_6-49-58.txt)

**Comment by miljan-aleksic** [comment]
The JS errors seems related to the PHP ones, but those are coming from K2 core code which we would recommend to report to them as it would be nice to get them fixed.

With errors reporting disabled, do you have any issue on mapping K2 content to the site?

**Comment by miljan-aleksic** [comment]
PHP errors can affect the workflow of the customizer and that be reflected as an JS issue. I'm just saying it seems related, but you don't have to report it, is just a suggestion as it's an error that affects all K2 users, not related to YOOtheme Pro :)

I have created a test view displaying a K2 Item and I am able to map the content and others, can you reproduce there the issues you mention?

https://dev.sane.org/ytptest

Make sure to keep error reports disabled and view the content as an admin or through the customizer.

**Comment by snaffle** [comment]
Ok it took me a while to work out that you'd mapped it to a Template in YTPro, which is all well and good and I can see that the content loads for a single post, but it's still not working on my Panel Slider in a builder page.

Can you go to Joomla core Content > Articles and have a look at the Home article which has been built using YTPro.

Can you have a look at the Panel Slider  which is in the section "Stories from the community" and is labelled "Stories slider".

There I have tried to map "K2 Items" to the People Like Us category that this article comes from and I have also tried to just map to the single K2 item and neither of them are pulling in the content.

 Or does it only work in the Templates section of YT Pro?

**Comment by miljan-aleksic** [comment]
Please try it now :)

**Comment by snaffle** [comment]
You sir, are an absolute legend! Thanks so much Miljan, I appreciate this more than you realise... 

Yootheme Pro has become my default development tool in my small web development business but I have a couple of largish old clients, this one included, who have large K2 based websites and I had started thinking about migrating them back to the Joomla core... which would have been a nightmare and this now means I don't have to worry about it! Well, at least for now.

Again, thanks for all your efforts on developing this add-on :-)

**Comment by snaffle** [comment]
I still think you're a legend but Extra Fields still seem to be a bit of a problem...

This particular category uses the "Cards Template" extra fields group in K2, which is showing up in K2 but is missing a lot of the extra fields.

I've attached a couple of screenshots showing the Extra Fields group in K2 and one showing the Source selector for that group, which only shows 3 fields.

I've highlighted a field, "Category Text", which I know this article has a value for and I was going to use to test the extra field, but it's not showing up... any ideas why?

Not critical for my current site so no rush on this but I thought I should mention it... thanks again for your work :-) 

![k2-cards-fields](https://user-images.githubusercontent.com/6090719/170454260-069f8a14-ef93-46da-93b6-41615f596c16.png)
![source-missing-k2-extra-fields](https://user-images.githubusercontent.com/6090719/170454314-6777136d-3312-49af-bcd3-99a30e4c4536.png)

**Comment by miljan-aleksic** [comment]
You are welcome Nathan! This addon is exactly meant for that, help those old sites transition to something better without stressing out, gradually.

Can you please test the Extra Fields in the test page I created before, are those complete there or also missing some?

**Comment by snaffle** [comment]
Sorry, ran out of time last night so I've had a look at the Extra Fields now in the Template manager and they're missing there too - screenshot attached.

In some good news though, I added one of the fields that does show up, "Category Image Alt Text" and it loads above the image correctly.

But yes a bit stumped by why those fields aren't showing up...

![k2-template-missing-fields](https://user-images.githubusercontent.com/6090719/170579993-aba6cbf4-4dca-4dea-80fd-98b7984bd97e.png)
![extra-field-displaying-correctly](https://user-images.githubusercontent.com/6090719/170580033-f237f6b5-58e2-4cde-a77d-65dc7b529f99.png)

**Comment by miljan-aleksic** [comment]
Thank you Nathan, I will be checking this next week :)

**Comment by miljan-aleksic** [comment]
Hi Nathan,

sorry it's crazy busy time for us, could you perhaps recreate this issue in a clean Joomla Installation and send me an Akeeba Backup of it? Working on it locally would definitely be easier.
